### ISSUE TITLE
EEPROM write fails after ~50 overwrites

### ISSUE THREAD

**Issue by avikde** [avikde/koduino#10]
This sketch

```
#include <EEPROM.h>

void debug() {
  Serial1 << millis() << "\t";
  for (int i=0; i<10; ++i)
    Serial1 << EEPROM.read(i) << "\t";
  Serial1 << "\n";
}

void setup() {
  Serial1.begin(115200);
  attachTimerInterrupt(0, debug, 10);
}

void loop() {
  for (int i=9; i>=0; --i)
    EEPROM.write(i, i);
  delay(1000);
  for (int i=9; i>=0; --i)
    EEPROM.write(i, 0);
  delay(1000);
}
```
works for about 50 seconds (overwrites) and then cannot change the value any more. I think we'd have to implement a smarter write that would cache and erase the page (sector on F4) if we want to be able to overwrite further. I don't *think* (to be checked) that the ST EEPROM emulation code EE_Write erases pages or sectors, so we'd need to add code that checks, caches existing data, erases the page, and then replaces the values.

See also: http://stackoverflow.com/questions/30774717/very-few-write-cycles-in-stm32f4

**Comment by gwenger** [comment]
Main problem came from using FLASH_Lock and FLASH_Unlock. There is probably some flag that needs to be cleared after locking the flash which causes future unlocks to fail. By removing the FLASH_Lock lines, writing to the EEPROM no longer fails. Technically this is a work around since it would be best to have the ability to lock/unlock the flash between writes, but it gets the job done for now.
