### ISSUE TITLE
micros() faults after 1000us

### ISSUE THREAD

**Issue by jduperret** [avikde/koduino#9]

**Comment by avikde** [comment]
Hi Jeff,

I think this bug is fixed now. As I suspected, the problem was interrupt priority, and it turns out that SysTick has a special way for setting interrupt priorities: http://electronics.stackexchange.com/questions/76299/stm32-interrupt-priority-preemption-problems (guess I wasn't the only person this tripped up).

Here is a MWE:
```
void testFunc() {
  uint32_t t0 = micros();
  delayMicroseconds(500);
  uint32_t t1 = micros() - t0;
  delayMicroseconds(500);
  uint32_t t2 = micros() - t0;
  Serial1 << "halfway " << t1 << ", fullway " << t2 << "\n";
}

void setup() {
  Serial1.begin(115200);
  attachTimerInterrupt(0, testFunc, 500);
}

void loop() {
}
```

Pre-latest-update, the output was:
```
halfway 4294966495, fullway 4294966995
halfway 500, fullway 4294967111
halfway 4294966334, fullway 4294966834
halfway 500, fullway 4294966950
```
After latest update, output is
```
halfway 499, fullway 1000
halfway 500, fullway 1000
halfway 500, fullway 1000
halfway 500, fullway 1001
halfway 500, fullway 1001
halfway 500, fullway 1000
```

Please test and let me know if there's a further issue. Otherwise I'll close this issue in a day or two.
